name: &this http-rfc7807
version: !include ./version.yaml
synopsis: |
  RFC7807 style response messages
description: |
  [RFC7807 — Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807)
  style response messages.

  See [GitHub README](https://github.com/trskop/http-rfc7807#readme) for more
  information.

github: trskop/http-rfc7807
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2020-2021 Peter Trško
category: Web, Servant

extra-source-files:
  - README.md
  - ChangeLog.md

default-extensions:
  - BlockArguments
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications

dependencies:
  - base >=4.12 && <5
  # ^ Version 4.12.0.0 is bundled with 8.6.*, we support GHC 8.6.5 for static
  # build.

ghc-options: ["-Wall", "-Wcompat"]

library:
  source-dirs: src

  dependencies:
    - aeson >=1.4.1.0
    # ^ Lower bound based on servant.
    - http-types >=0.12.2 && <1
    # ^ Version 0.7.0 is the first one that provides hContentType that we are
    # using, but servant requires newer version (>=0.12.2).
    - http-media >=0.7.1.3 && <1
    # ^ Lower bound based on servant.
    - servant >=0.16 && <1
    # ^ Version bounds to match servant-server.
    - servant-server >=0.16 && <1
    # ^ ServantErr was renamed to ServerError in version 0.16.
    - text >=1.2.3.0 && <2
    # ^ Lower bound based on servant.
    - wai >=3.2.1.2 && <4
    # ^ Lower bound based on servant-server.

tests:
  command-wrapper-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
      - *this

      - HUnit >=1.6.0.0 && <1.7
      # ^ Same bounds as `hspec-expectations-json` has.
      - call-stack >=0.2.0 && <1
      - hspec-expectations-json >=1.0.0.0 && <2
      # ^ At the moment of writing 1.0.0.0 is the only version available.
#     - quickcheck-instances
      - tasty >=1.2.3 && <2
      # ^ Lower bound is the version available in LTS 16.20
      - tasty-hunit >=0.10.0.2 && <1
      # ^ Lower bound is the version available in LTS 16.20
#     - tasty-quickcheck

      # Same dependencies as the library:
      - aeson >=1.4.1.0
      - http-types >=0.12.2 && <1
      - servant >=0.16 && <1
      - servant-server >=0.16 && <1
      - text >=1.2.3.0 && <2

    ghc-options: ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
